### ISSUE TITLE
Rate-limiting all views

### ISSUE THREAD

**Issue by jplehmann** [jsocol/django-ratelimit#103]
This is a feature request / solicitation for advice.

I was looking for something like this except I don't necessarily want to apply it per view but for my whole site.  I didn't see that this is possible with `django-ratelimit` but it doesn't seem like that would be a difficult extension. Is there a reason this isn't an option? Is it a bad idea?

**Comment by jsocol** [comment]
Django Ratelimit provides access to the [`is_ratelimited`](https://django-ratelimit.readthedocs.org/en/latest/usage.html#helper-function) method to build more unique functionality than is included in the library.

You could use `is_ratelimited` to write middleware that would use `is_ratelimited` to check _all_ views, but I've never seen a case where literally _all_ views were meant to be ratelimited together in the same bucket. That would include things like 404 pages and registration/login/logout, terms of service, etc. Even if you are only serving API endpoints, it would catch things like issue/revoke token.

You can also use the [`group=`](https://django-ratelimit.readthedocs.org/en/latest/usage.html#ratelimit) kwarg to `@ratelimit` to group many endpoints together so that calls to any of them count against a global ratelimit. Which route you go depends on your needs.

**Comment by jplehmann** [comment]
Awesome, thanks for the fast response.

If someone is abusively crawling my site, I am fine blocking 100% access
for a time.  That's the use case I envision.  Maybe it's more nuanced than
I realize.

Would you like me to contribute back the middleware?

**Comment by jsocol** [comment]
You'll need to do quite a bit more work to be able to block an individual user. Ratelimits are counted per-IP or per-user, but they cannot be individually set. If you're interested in blocking abusive requests by IP, something further up the stack like firewall blackholes (something like fail2ban might be able to automate it) is probably a better choice.

**Comment by jplehmann** [comment]
I would have liked a solution further up the stack, however I'm using
Heroku and they claim that DDOS attack protection and the like must be done
within the application. So I'm stuck with using a middleware solution. My
plan was to block on IP basis (not user).  Do you think that could work?

The main problems I could see would be a) a smart misuser somehow
hiding/spoofing his IP, which you have written some about, and 2) an IP
that might represent a set of people, but I think this is unlikely for my
site.

I welcome other thoughts as you're a lot more experienced with this than
me.  Appreciate it.

**Comment by jplehmann** [comment]
Hi @jsocol, I tested with decorator usage and it worked as expected. However using the helper function in middleware as follows:
```
    def process_request(self, request):
        if is_ratelimited(request, group="all", key='user_or_ip', rate='2/m', method='ALL', increment=True):
            log.warn("Request is over rate-limit: %s", request)
        else:
            log.warn("Just checked")
```
Does not appear to work.  One refresh is generating a dozen or so requests (Just checked 10+ times) and thus on the second refresh (or sooner) it should be blocked.  It does not appear to be incrementing, and the "request over limit" message is never logged.  What's going wrong here?

**Comment by jsocol** [comment]
I'm afraid I don't have time to help debug things like this. Double check the cache settings?

**Comment by jplehmann** [comment]
To be clear, I'm no longer asking for advice/help as in earlier, I think this is a bug. I'll open a separate issue.
