### ISSUE TITLE
is_ratelimited increment=True does not seem to work

### ISSUE THREAD

**Issue by jplehmann** [jsocol/django-ratelimit#104]
I tested with decorator usage and it worked as expected (with the exception of issue #73). However using the helper function in middleware as documented:

```
    def process_request(self, request):
        if is_ratelimited(request, group="all", key='user_or_ip', rate='2/m', method='ALL', increment=True):
            log.warn("Request is over rate-limit: %s", request)
        else:
            log.warn("Just checked")
```

Does not appear to work in that the "over limit" message is never displayed, despite `increment=True`.

I believe my caching is working fine since as I stated, the decorator behaves properly.  I am moving forward using the decorator so it's not urgent for me.

**Comment by jsocol** [comment]
I'm pretty sure `method='ALL'` is the problem here. `'ALL'` as a string will try to match requests with the HTTP verb "ALL". Try `method=ratelimit.ALL` which is a special value, not a string. Or just omit the parameter, since `ALL` is the default.

Please feel free to re-open if this is still an issue and the above doesn't fix it.
