### ISSUE TITLE
How to throttling a view depending on the accessed object?

### ISSUE THREAD

**Issue by brunohkbx** [jsocol/django-ratelimit#140]
I have an API with this endpoint
`api/v1/personal_trainers/{personal_trainer_pk}/invites/{pk}/resend_email/`

I have tried something like that:

```
@ratelimit(key='user' rate='5/m', block=True)
@detail_route(methods=['post'])
def resend_email(self, request, personal_trainer_pk, pk=None):
    invite = get_object_or_404(Invite, pk=pk, personal_trainer_id=personal_trainer_pk)

    SendInviteEmailService(invite).send_email()

   return Response(status=status.HTTP_200_OK)
```

But I need to block by invite's PK instead of user.
Is it possible to limit the access using this lib?

**Comment by jsocol** [comment]
You can use the [`is_ratelimited`](https://django-ratelimit.readthedocs.io/en/latest/usage.html#helper-function) utility method within the view and potentially a [callable `key`](https://django-ratelimit.readthedocs.io/en/latest/keys.html#callable-values) and/or the group to achieve this. But beware that using ratelimit inside a DRF-wrapped view is a little tricky, since the `request` object isn't a Django/wsgi Request, but a DRF-specific request

**Comment by brunohkbx** [comment]
I have tried it also.
The PK value is inside the kwargs and I don't know how to pass it to the key propertie.

**Comment by brunohkbx** [comment]
Hey @jsocol, thanks.
Solved it using is_ratelimited

```
if is_ratelimited(
    request,
    'invites',
    key=lambda group, request: self.kwargs['pk'],
    rate='1/h',
    increment=True
):
   return Response(status=status.HTTP_429_TOO_MANY_REQUESTS)
```
