### ISSUE TITLE
implement different rate limit messages for different views.

### ISSUE THREAD

**Issue by AigerXD** [jsocol/django-ratelimit#188]

**Comment by AigerXD** [comment]
when rate limiting for different views it should give different rate limit messages. for example  Signup view and forgot password view, rate limit messages should be different. 
if i am rate limiting signup view  for '1/m' and rate limiting the forgot password view for '5/d'. then the rate limit messages should be different.

**Comment by jsocol** [comment]
Hi @AigerXD, thanks for the question. I don't _think_ this is in scope for django-ratelimit, but let me make sure I understand the situation:

You have two views, e.g. `def signup()` and `def forgot_password()` and both are wrapped with `@ratelimit()` decorators, and—when a ratelimit error occurs—you'd like those to display distinct error pages. Is that right?

The `@ratelimit` decorator raises a `Ratelimited` exception, which is a subclass of Django's `PermissionDenied` exception. This means that, without any additional configuration, a ratelimit error will use the same `handler403` view as other `PermissionDenied` errors.

That makes it quick to install django-ratelimit, but does, as you've seen, have some limitations. For example, since ratelimit was created, `HTTP 429 Too Many Requests` has become a standard, but Django's `handler403` understandably doesn't send that status code. (I'm considering if it's worth adding a very basic `handler429`-type view and it might be.)

Another limitation is that, by default, Django will use one error view for all sorts of errors. One option is to examine the request and the exception in that view, e.g.

```py
def handle_403(request, exc):
    if isinstance(exc, Ratelimited):
        return render('ratelimited_error.html')
```

Another option is to configure a `RATELIMIT_VIEW` and use [the `RatelimitMiddleware`](https://django-ratelimit.readthedocs.io/en/stable/usage.html#middleware). Though that view will still have to pay attention to which path the user was originally on.

Finally the best option is probably not to use the decorator at all, but to switch to [`is_ratelimited`](https://django-ratelimit.readthedocs.io/en/latest/usage.html#core-methods), e.g.

```py
def signup(request):
    if ratelimit.core.is_ratelimited(request, group='signup', rate='5/m', key='ip', increment=True):
        return render(request, 'signup_ratelimit.html', status=429)

def forgot_password(request):
    if ratelimit.core.is_ratelimited(request, group='forgot_password', rate='1/m', key='ip', increment=True):
        return render(request, 'forgot_ratelimit.html', status=429)
```

I don't think it's possible for django-ratelimit to be able to know about all the potential uses people have and what kind of responses to show (what content or even content-type). But the tools are there to build the type of responses you want.

**Comment by jsocol** [comment]
If I summarized the issue incorrectly, definitely feel free to reopen!

**Comment by EchChou** [comment]
Hello,
I'am trying to use **is_ratelimited** instead the decorator but I get this error :
_'function' object has no attribute 'core'_
Can you help me please.

**Comment by EchChou** [comment]
Hello,
I'am trying to use **is_ratelimited** instead the decorator but I get this error :
_'function' object has no attribute 'core'_
Can you help me please.

**Comment by EchChou** [comment]
Hello,
I'am trying to use **is_ratelimited** instead the decorator but I get this error :
_'function' object has no attribute 'core'_
Can you help me please.
