### ISSUE TITLE
Why use a new cache key for every window?

### ISSUE THREAD

**Issue by laixintao** [jsocol/django-ratelimit#196]
Hi @jsocol I read the source code and it's excellent!

I have one question and can't figure out by myself, beg you for some clues :)

So if I implemented a rate limit, I will the same key for every time window, and reset it in a new time window. E.g. I will `set rate_limit:ip 0 expire 1hour`, then `incr rate_limit 1` for every request. Then `set rate_limit:ip 0 expire 1 hour` again in a new hour.

I saw that you use a different key for every window, I think your way is better, but I just can't figure out why. Can you come up with the drawbacks of my "expire the same key for every windows" method?

Thanks a lot.

**Comment by jsocol** [comment]
The biggest reason is to remove the need for synchronization when running the application code on multiple hosts. Something would have to keep track of what time it was, and whose job it was to reset the limit—otherwise _several_ hosts might reset the limit. And you'd have to know when the key was initially set, which would have to be tracked somewhere, either in process memory (which might be lost in a restart) or in a shared place like the cache.

This way, it's not quite share-nothing, but the only point of synchronization is the cache server itself (which can be sharded based on the cache key). There's no risk of two hosts trying to reset the key at the same time since ratelimit only relies on (theoretically) atomic cache operations. There's no need to keep track of how much time has passed. Given whatever I believe to be the time right now, I can calculate the key independently and try to `add` or `incr` it.

**Comment by jsocol** [comment]
Thanks for the question!

**Comment by laixintao** [comment]
Thanks for the answer!
