### ISSUE TITLE
Add `block_for` argument in @ratelimit

### ISSUE THREAD

**Issue by Ashish-Bansal** [jsocol/django-ratelimit#203]
#### Description

```
def ratelimit(group=None, key=None, rate=None, method=ALL, block=False, block_for: int = -1):
    pass
```

In case, `block_for` (in seconds) is mentioned, when rate limiter is triggered, we will block requests for that user/ip/key for `block_for` seconds. 

#### Usecase

It would be more efficient for rate limiting and blocking scraping bots and spammers.

**Comment by jsocol** [comment]
Hi, thanks for the suggestion! I think this would take a fairly significant change to how ratelimit works under the hood, and I'm not sure I see the benefit over using a longer window (as soon as `block_for` seconds expire, you'd be able to do a burst again). I don't think it's worth the complexity or the extra argument.

If you want to block bots and spammers but be gentler on real people, I recommend setting an overall limit and a burst limit. E.g. if you want to allow 100 reads/hour, consider setting a burst limit of 10 reads/minute:

```py
@ratelimit(rate='100/h')
@ratelimit(rate='10/m')
def my_view(request):
    pass
```

Burst limits will frustrate bots, since they'll hit them very quickly and frequently, but won't stop real people from reaching the real limit.

**Comment by Ashish-Bansal** [comment]
>  I'm not sure I see the benefit over using a longer window

Hm true, even I wasn't easily able to realise its benefit. May be it's really not-a-standard way of the rate limiting. 

Here's my thoughts regarding the same - 

```
@ratelimit(rate='10/m')
def my_view(request):
    pass
```

Above rate limiting means block the burst requests in short time interval and let them resend requests after that interval.

---

```
@ratelimit(rate='100/h')
def my_view(request):
    pass
```

Above rate limiting means having longer window interval for counting requests and blocking the requests for that same interval.

---

```
@ratelimit(rate='100/h')
@ratelimit(rate='10/m')
def my_view(request):
    pass
```

^means having both the longer and burst window intervals together and blocking the requests for the same interval.

---

But let's say I want to count requests for the shorter period but block the respective entity for the longer periods, how can I achieve the same ? That's what my intention is for introducing `block_for` param. May be it's super specific to my usecase and not a generic stuff. 

Anyway, I really needed that thing, so I added a prototype yesterday for internal use - https://github.com/jsocol/django-ratelimit/compare/main...leetcode:add_option_to_block_requests

**Comment by jsocol** [comment]
Yeah I think this might be too esoteric to build in here. You could use some of the tools in this library to implement a block at another layer—e.g. trigger fail2ban or set a flag that's used by custom middleware. Or if your fork works for you, that's great! But it's a lot of network back and forth to add for a very uncommon use case.

**Comment by Ashish-Bansal** [comment]
> But it's a lot of network back and forth to add for a very uncommon use case.

As for this^, IIRC it would involve one additional network call only in case if user has specified `limit_for` argument.

> Yeah I think this might be too esoteric to build in here. You could use some of the tools in this library to implement a block at another layer—e.g. trigger fail2ban or set a flag that's used by custom middleware. Or if your fork works for you, that's great! 

Hm, I'll think about moving it out of the codebase so that I don't have to maintain the fork. And also, thanks for your review, appreciate it!

**Comment by benjaoming** [comment]
With django-stopforumspam, we use a facilitated list of IPs to get rid of form post spammers: https://github.com/benjaoming/django-stopforumspam

If you find a way, you can add additional IPs to that list locally (with a Django model). This is likely only viable for POST requests because it's 1) costly to do DB look-ups for every GET request and 2) also costly to flush the whole IP list in to the HTTP servers / system's deny lists.
