### ISSUE TITLE
django-ratelimit keeps incrementing keys in cache even though limit has been reached and 429 sent

### ISSUE THREAD

**Issue by necrolingus** [jsocol/django-ratelimit#215]
Hi there

**Versions used**
Python Version: 3.7.5
Django==2.2.13
django-ratelimit==3.0.1

**I have the following code:**

```
@ratelimit(key='post:username', rate='4/h', block=True)
@ratelimit(key='post:tenant', rate='4/h', block=True)
@csrf_exempt
def index(request):
    print(request.POST["username"])
    print(request.POST["tenant"])
    print("")
    return HttpResponse('hallo', content_type='text/plain', status=200)
```

**I use the following cache in settings.py for django-ratelimit:**

`'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 
		'LOCATION': 'unique-snowflake',
		'TIMEOUT': 100,
	}`

**Then I performed a series of requests**
user1/CH means the username value is user1, and the tenant value is CH
**Request 1:**
user1/CH
200 response

**Request 2:**
user1/CH
200 response

**Request 3:**
user1/CH
200 response

**Request 4:**
user1/CH
200 response

**Request 5:**
429 response. Correct behavior
Even though tenant CH is now rate limited, I decided to keep sending but I changed the user to "user2"

**Request 1:**
user2/CH
429 response

**Request 2 :**
user2/CH
429 response

I decided here that OK, let me change my tenant to TC, but keep using using user 2
**Request 1:**
user2/TC
200 response

**Request 2:**
user2/TC
200 response

**Request 3:**
429 response. Not correct as my rate limits are 4 for tenant and 4 for username.

Keep in mind the rate limit is 4 for tenant and username, but because tenant CH used user2 twice (after it was already rate limited), tenant TC got rate limited after only 2 attempts which is incorrect. This leads me to believe that django-ratelimit, even though it rate limited the CH tenant, still kept on updating the keys in the cache which should not be the intended behavior. It should ideally not update any cache and just rate limit.

This can lead to malicious user/bad code/etc to just keep on sending requests even after a 429 is received, and in this case, locking out tenants or users.

**Comment by jsocol** [comment]
Hi there! I think there might be some confusion about how multiple ratelimits interact, and how the cache keys get set/rotated.

Multiple limits are ORed together—that is, if you fail any of them, you fail—but order matters. In this case, the outer limit, `post:username`, is tested first, then the tenant is tested. If the user succeeds, it counts as an attempt, regardless of what happens later. That's why the `user` keeps accruing attempts. If you want tenant to count first, you could re-order the decorators. However...

If you want a single limit to the `(username, tenant)` pair, you could combine the two fields with custom logic, by creating a [callable key](https://django-ratelimit.readthedocs.io/en/latest/keys.html#callable-values) that returned some combination of tenant and username (maybe `{tenant}\u04{username}` or hash them together).

In terms of locking out tenants, there are a couple of things:

First, ratelimit uses a staggered fixed-window strategy, instead of a sliding windows. So based on the rate, the period, the key value, and the group, there'll be some calculated window. For example, for 1 hour, 11:03:29 will be the reset time, and the next reset time for that same combination will be 12:03:29, then 13:03:29, etc... The downside is that you if you had a limit of `100/h`, you could do 200 requests in a short span around the reset point. The upsides are that the calculation is share-nothing and can be done independently, the window reset even if you accidentally try again a little too early.

Second, yes if you're doing hard blocks on user-supplied data like username (instead of e.g. using the authenticated user) it creates a [denial-of-service vector](https://django-ratelimit.readthedocs.io/en/latest/security.html#denial-of-service). Where possible, another option is to use `block=False`, and do something like require a captcha rather than fully blocking.

**Comment by necrolingus** [comment]
Hi jsocol

Thanks so much for the detailed explanation and taking the time to write it (and so quickly after my post as well!). I had a suspicion that my understanding might have been incorrect, and your answer confirms that. Now I can sleep easy that I know exactly how this works.

I had a brief look at the documentation for callables, and it seems that it will solve my dilemma as I can essentially return my own key(s) like you said. Very powerful.

I am going to close this bug I submitted as it is not a bug...

Thanks again and thanks for such an awesome python package! 

Stay safe and keep well.

**Comment by necrolingus** [comment]
It was not an issue, my understanding about how stacked keys work was wrong. Jsocol explained it in much details and now it is all good.
