### ISSUE TITLE
X-Forwarded-For

### ISSUE THREAD

**Issue by jabbawookiees** [jsocol/django-ratelimit#216]
Does this respect the `X-Forwarded-For` header provided by proxies? It seems to only check `request.META['REMOTE_ADDR']`

**Comment by jsocol** [comment]
Hey @jabbawookiees, django-ratelimit [does not support X-Forwarded-For](https://django-ratelimit.readthedocs.io/en/stable/security.html#client-ip-address) directly because the methods that different environments, deployment configurations, and software use to convey the client IP address are varied and inconsistent. Django briefly had `SetRemoteAddrFromForwardedFor` middleware in 1.0, but it was dropped years ago in 1.1 for the same reason.

There is an idea in #208 that could make it easier to configure the source of the client IP. That will—intentionally—require user-land code to match the specific deployment.
