### ISSUE TITLE
`mixins.py` removed from `4.0`

### ISSUE THREAD

**Issue by sobolevn** [jsocol/django-ratelimit#278]
Hi! First of all, thanks a lot for this package. I am using it for several years, it always was great.

But, I have a problem after the recent `4.0` release. Here's how my code was using this package:

```python
from ratelimit.mixins import RatelimitMixin

class UserUpdateView(RatelimitMixin, UpdateView[User, UserUpdateForm]):
    form_class = UserUpdateForm
    success_url = reverse_lazy('identity:user_update')
    model = User

    # Rate-limiting:
    ratelimit_key = 'ip'
    ratelimit_rate = '10/h'
    ratelimit_block = True
    retelimit_method = ['POST', 'PUT']  # GET is safe
```

I really loved this pattern, because of how easy it was to mock in tests. For example, I could disable rate limiting with:

```python
@pytest.mark.django_db()
@pytest.mark.parametrize('field', User.REQUIRED_FIELDS + [User.USERNAME_FIELD])
def test_user_update_missing_required_field(
    field: str,
    monkeypatch: MonkeyPatch,
) -> None:
    """Test missing required will fail the registration."""
    # Since we send multiple empty requests, we need to switch rate limit off for this test.
    monkeypatch.setattr(UserUpdateView, 'ratelimit_block', None)
```

Or I could simplify rate-limiting logic in tests, so I can make it much faster (changing `ratelimit_rate = '10/h'` to `ratelimit_rate = '1/h'` makes a test 10x faster with no semantics changed):

```python
@pytest.mark.django_db()
def test_user_update_rate_limit(
    monkeypatch: MonkeyPatch,
) -> None:
    """Test that too many http requests will trigger a rate limit."""
    # Just a single request will be fine, more requests = slower.
    max_requests = 1
    monkeypatch.setattr(
        UserUpdateView,
        'ratelimit_rate',
        '{0}/h'.format(max_requests),
    )
```

Now, with decorators as the main API - I don't see how I can do this.
Because right now it is so much harder to mock things in tests. I see a way to mock `django_ratelimit.core.is_ratelimited` function or views' `get`/`post` functions.

So, please can we please (either or both):
1. Return `mixins` in `4.1` release? 🙏 
2. Document how can users now do the same things in tests with the new API?

**Comment by jsocol** [comment]
Hi @sobolevn—the `RatelimitMixin` has actually been gone for a while, since #170, and originally released in v3.0.0.

The `RatelimitMixin` approach was never as powerful and was more fragile than the decorator approach, so I'm not too eager to return it. My general suggestion for tests would be to flip the `RATELIMIT_ENABLE` [setting](https://django-ratelimit.readthedocs.io/en/v4.0.0/settings.html#ratelimit-enable) to `False` and not worry too much about it.

I'd recommend against tests like the last example: that is really testing `django_ratelimit` and not your own code. Removing tests of library functionality and relying on the library's tests will help keep the test suite quick.

Another option might be to write your own version of the mixin. There are a few tools—the decorator as well as `is_ratelimited` and `get_usage` in `django_ratelimit.core`—that are there exactly for this reason: to enable users to write their own code around the library when the library doesn't support their use case.
