### ISSUE TITLE
What does "annotate" request mean?

### ISSUE THREAD

**Issue by Schwankenson** [jsocol/django-ratelimit#83]
Hello,

I don?t understand what happens with a request if block is False.

I created a stackoverflow thread for it:
http://stackoverflow.com/revisions/32608010/2

**Comment by jsocol** [comment]
`block=True` will cause an exception<sup>1</sup> that ends request processing. `block=False` adds an attribute to the request, `request.limited`, that is either `True` or `False`. This allows views to respond differently to ratelimited-requests. For example, a login form may decide to add a CAPTCHA rather than prevent login entirely, to avoid a DOS vector against a specific IP or user.

<sup>1</sup>: The exception extends Django's `PermissionDenied`, so by default it causes a 403 response. It can also be handled by `RatelimitMiddleware` to use a [custom error view](https://django-ratelimit.readthedocs.org/en/latest/usage.html#middleware).

**Comment by Schwankenson** [comment]
Thank you for this quick answer. I will quote it on stackoverflow...
