### ISSUE TITLE
How's the period (expiry / timeout) information set in the cache

### ISSUE THREAD

**Issue by bitcity** [jsocol/django-ratelimit#84]
In a previous version (0.4.0), the cache expiry was set explicitly like this in `helpers.py`

    cache.set_many(counts, timeout=timeout)

where timeout was derived by splitting the rate into `count` & `period`. 

In the current version (0.6.0), the file `utils.py` still splits the rate into count (limit) & period, but the period information is not conveyed to the cache.

**Comment by jsocol** [comment]
The method of counting over time changed. Instead of relying on cache expiry (which leads to situations where good actors get blocked forever by being just a little too eager) ratelimit now calculates [a fixed window](https://github.com/jsocol/django-ratelimit/blob/master/ratelimit/utils.py#L72-L81) that is `period` seconds long, and the cache key itself changes every `period` seconds.

**Comment by jsocol** [comment]
See also [the CHANGELOG](https://github.com/jsocol/django-ratelimit/blob/master/CHANGELOG#L17), issue #48, and the [upgrade notes](https://django-ratelimit.readthedocs.org/en/latest/upgrading.html).

**Comment by bitcity** [comment]
> cache key itself changes every period seconds

Oops, I overlooked this part. 

However, I still have some doubt. Django has a default `timeout` for cache = 300 seconds. Say I have a couple of ratelimit decorators, where the slowest rate (& largest period) is `5/h` (i.e. 5 requests per hour). Won't the key be lost after 300 seconds unless I explicitly change the timeout setting to be greater than than say 1 hour ?

**Comment by jsocol** [comment]
> Won't the key be lost after 300 seconds unless I explicitly change the timeout setting to be greater than say 1 hour ? 

Can you please test this and if so file a bug? No one has reported this issue.
