### ISSUE TITLE
Cache TIMEOUT should be higher than the largest period specified in rate

### ISSUE THREAD

**Issue by bitcity** [jsocol/django-ratelimit#85]
Django specifies a default timeout of [300 seconds](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-CACHES-TIMEOUT). If there are ratelimit decorators that have a rate with a period that exceeds this number e.g. `5/h` (i.e. 5 requests per hour), would the key expire after Timeout & be eventually overwritten depending on the cache expiration policy ? I tried to re-create this scenario using `backends.locmem.LocMemCache` however after the expiry time, the key was still accessible. Perhaps its marked as stale and is not reliable. I'm not sure how other backends will behave. 

It would be nice if `django-ratelimit` can look at the `settings.CACHES` and alert if `TIMEOUT` is lesser than the largest period specified in rate.

**Comment by jsocol** [comment]
@bitcity It's a lot more helpful when filing bugs if you have ever actually reproduced the issue, not just if you have a hunch.

If you can reproduce this, then the right response isn't to worry about the default `TIMEOUT` value in the settings, but to set the timeout explicitly such that it's slightly longer than the period.

**Comment by tdhooper** [comment]
I've reproduced the issue in a test https://github.com/jsocol/django-ratelimit/pull/87

**Comment by SimonSteinberger** [comment]
This is an extremely critical issue, which breaks the whole functionality of the app. Such an issue should have been fixed immediately!

I thought the app was properly field tested and safe, but it's not. By the way, you may want to read up on another issue in Simon Willison's (co-founder of Django) blog post about this type of rate limiting:
http://blog.simonwillison.net/post/57956846132/ratelimitcache

The other issue is: Imagine a rate limit of 5,000/h. That's not uncommon, e.g. for an API. What about if a user makes 5,000 requests just a minute before the cache key expires and none before? Right after that, he can make another 5,000 requests. Which results in almost 10,000 requests/h. Thus, the rate limit was breached.

**Comment by willkg** [comment]
> This is an extremely critical issue, which breaks the whole functionality of the app. Such an issue should have been fixed immediately!
> 
> I thought the app was properly field tested and safe, but it's not.

Please fix it, pay someone to fix it, go use a different library or otherwise be less of an entitled whinypants.

**Comment by jsocol** [comment]
OK, I have a lot things to say about this, but I don't know if they're productive. So here are the very dry responses:

> This is an extremely critical issue

A workaround exists, which is to set the default `TIMEOUT` in `CACHES` to `None`, either on the `default` cache or to [set up another entry](https://django-ratelimit.readthedocs.org/en/latest/settings.html) specifically for ratelimit. It's not a particularly complex workaround, and its existence lowers the severity a lot.

> I thought the app was properly field tested and safe

Please feel free to contribute tests. Or use a different library that you feel safer with.

> http://blog.simonwillison.net/post/57956846132/ratelimitcache

This library was actually based on that blog post. There [was a reference in the README](https://github.com/jsocol/django-ratelimit/commit/1fcd78591f065e30cc7c1c33d8a8bb8116700601#diff-88b99bb28683bd5b7e3a204826ead112L128) that got lost in the push to have real docs. It has, after all, been 6 years since Simon wrote that.

> The other issue is: Imagine a rate limit of 5,000/h. That's not uncommon, e.g. for an API. What about if a user makes 5,000 requests just a minute before the cache key expires and none before? Right after that, he can make another 5,000 requests. Which results in almost 10,000 requests/h. Thus, the rate limit was breached.

This is a [separate issue](https://github.com/jsocol/django-ratelimit/issues/new) but [it is correct, documented behavior](https://django-ratelimit.readthedocs.org/en/latest/upgrading.html#fixed-windows). This style of window is much kinder to good actors who try to implement reasonable back-offs—the other style can keep them limited forever. The _average_ number of req/h is still 5k in your example, with bursts possible. Adding another, per-minute or per-sec (or per-5min or something) limit will allow you to tune the bursts more specifically to your needs.

**Comment by jsocol** [comment]
#112 addresses this.
