### ISSUE TITLE
Document how to send a 429 response instead of 403

### ISSUE THREAD

**Issue by nferrari** [jsocol/django-ratelimit#89]
As defined on the [RFC6585](https://tools.ietf.org/html/rfc6585), a 429 HTTP response stands for **Too many requests**.

If that's ok for you, I'll submit a PR.

**Comment by jsocol** [comment]
There are two ways to achieve this right now:

1. Use the [`RatelimitMiddleware`](https://django-ratelimit.readthedocs.org/en/latest/usage.html#middleware) and a custom `RATELIMIT_VIEW` that returns 429.
2. The [`Ratelimited`](https://django-ratelimit.readthedocs.org/en/latest/usage.html#ratelimit.exceptions.Ratelimited) exception extends `PermissionDenied`, so a custom `handler403` could also return 429 for this exception type.

I don't [see any way](https://github.com/django/django/blob/1.8.1/django/views/defaults.py#L67) to coerce the built-in 403 handler to send anything other than a 403.

I don't think we should ship a default error view because we can't know what content-type (json/xml/html) or shape of data to send back for a given API or endpoint. So right now we do it a little wrong, with little code. I suspect this would involve writing more code and imposing new requirements to be only very slightly less wrong.

Maybe it's worth explicitly calling out in the docs, though? "Want 429? Here's how..."

How would you go about it, @nferrari?

**Comment by nferrari** [comment]
OK without a default view, this won't be possible indeed. I'll go for the first solution you're suggesting (seems the cleanest to me).

Thank you!

**Comment by jsocol** [comment]
Going to leave this open to put a "how to do this" section in the docs.



--

**Comment by nferrari** [comment]
If I can help, here is my custom view:

```python
#coding:utf-8

from django.http import HttpResponse
from django.template import loader


class HttpResponseTooManyRequests(HttpResponse):
    status_code = 429

def ratelimited(request, exception):
    template = loader.get_template('429.html')
    return HttpResponseTooManyRequests(template.render(request=request))
```

**Comment by mlissner** [comment]
Perhaps a more modern Django way to do this is:
```
def ratelimited(request, exception):
    return render(request, '429.html', {'private': True},
                  status=HTTP_429_TOO_MANY_REQUESTS)
```

**Comment by supermitch** [comment]
I'm curious, is there any reason (I see nothing [here](https://django-ratelimit.readthedocs.io/en/latest/usage.html#exceptions)) why you raise a 403 instead of a 429?

**Comment by jsocol** [comment]
> I'm curious, is there any reason (I see nothing [here](https://django-ratelimit.readthedocs.io/en/latest/usage.html#exceptions)) why you raise a 403 instead of a 429?

This library actually [predates](https://github.com/jsocol/django-ratelimit/commit/0788adfa212acbb6b798e4135a3400fca0615397) RFC6585 that standardized 429 by about a year (even the MDN doc for it only [dates to 2017](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429$history)). At that point, 403 was probably the most common but people were also using custom statuses (c.f. Twitter's `420 Enhance Your Calm`) or webdav statuses.
