### ISSUE TITLE
Any way to whitelist/temporarily remove or alter ratelimit?

### ISSUE THREAD

**Issue by dan-passaro** [jsocol/django-ratelimit#95]
Say for example we limit account signups to 20 per hour per IP, but then a few months down the road we hold a conference that provokes say 100 signups within the hour. I know `cache.clear()` can be a crude way to reset the ratelimit restrictions, but is there anyway to tell this software, say, "For the next hour, don't limit IP nnn.nn.nn.nnn"? Or limit them to 1000/hr?

**Comment by jsocol** [comment]
Yes, though it's a pain, and requires jumping through a lot of hoops, so it
may not be worth it (if deploys are easy, it may be a lot easier to just
deploy the higher ratelimit for an afternoon).

Here's what you gotta do: use callable rate values
http://django-ratelimit.readthedocs.org/en/latest/rates.html#callables.

The problem is that you'll need to write some callable that can do the job.
If it's a fixed IP address you know in advance, maybe that's easy.
Otherwise, you'll need to put something into some non-volatile data store
to read and say "oh if it's this IP, return 1000/h, otherwise return 20/h".

Providing a batteries-included implementation of this is the goal of #52
https://github.com/jsocol/django-ratelimit/issues/52, though I admit I
don't have an ETA or anything on that. There's a very, very incomplete
example there that may be a useful starting point.
